# Generated by Django 4.2.4 on 2024-01-31 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                ('un', models.CharField(choices=[('UN', 'Unit'), ('KG', 'Kilogram'), ('M', 'Meter'), ('L', 'Litre'), ('RL', 'Roll'), ('PCT', 'Package')], default='UN', max_length=3, verbose_name='Measurement Unit')),
                ('description', models.CharField(max_length=120, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('icms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ICMS')),
                ('ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IPI')),
                ('st', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ST')),
            ],
        ),
    ]
