# Generated by Django 4.2.4 on 2024-03-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=40, unique=True, verbose_name='Code'),
        ),
    ]
