# Generated by Django 4.2.4 on 2025-02-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_alter_contract_control_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='change_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Change Reason'),
        ),
    ]
