# Generated by Django 4.2.4 on 2025-03-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_contract_change_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='approved_value',
            field=models.TextField(blank=True, null=True, verbose_name='Approved Value'),
        ),
    ]
