# Generated by Django 4.2.4 on 2024-06-26 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maintenances", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenance",
            name="approver",
        ),
    ]
