# Generated by Django 4.2.4 on 2024-12-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0007_maintenance_motive_denied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='company',
            field=models.CharField(choices=[('Gimi', 'Gimi'), ('GBL', 'GBL'), ('GPB', 'GPB'), ('GS', 'GS'), ('Filial', 'Filial')], default='Gimi', max_length=6, verbose_name='Company'),
        ),
    ]
