# Generated by Django 4.2.4 on 2025-02-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0008_alter_maintenance_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='want_validate',
            field=models.BooleanField(default=False, verbose_name='Want Validate'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Denied', 'Denied'), ('Canceled', 'Canceled'), ('Validation', 'Validation')], default='Opened', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='email',
            field=models.CharField(max_length=120, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='extension',
            field=models.CharField(max_length=120, verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='phone',
            field=models.CharField(max_length=120, verbose_name='Phone'),
        ),
    ]
