# Generated by Django 4.2.4 on 2024-03-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_remove_service_execution_date_service_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="provider",
            field=models.CharField(max_length=120, verbose_name="Provider"),
        ),
    ]
