# Generated by Django 4.2.4 on 2024-03-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0006_alter_service_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Approval Date"),
        ),
    ]
