# Generated by Django 4.2.4 on 2024-04-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='control_number',
            field=models.IntegerField(default=0, verbose_name='Control Number'),
        ),
    ]
