# Generated by Django 4.2.4 on 2024-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_service_control_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Value'),
        ),
    ]
