# Generated by Django 4.2.4 on 2024-09-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0011_service_control_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="motive",
            field=models.TextField(verbose_name="Motive"),
        ),
    ]
