# Generated by Django 4.2.4 on 2024-12-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_service_motive'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='motive_denied',
            field=models.TextField(blank=True, null=True, verbose_name='Motive Denied'),
        ),
    ]
