# Generated by Django 4.2.4 on 2024-12-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_service_company'),
        ('services', '0014_alter_service_company'),
    ]

    operations = [
    ]
