# Generated by Django 4.2.4 on 2025-02-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_service_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='approval_date',
            new_name='approval_date_director',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='approver',
            new_name='approver_director',
        ),
    ]
