# Generated by Django 4.2.4 on 2025-04-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_service_company'),
        ('services', '0015_merge_20241223_0825'),
    ]

    operations = [
    ]
