# Generated by Django 4.2.4 on 2024-02-26 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0002_remove_department_code_alter_department_id"),
        ("users", "0005_alter_user_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="departments.department",
                verbose_name="Department",
            ),
        ),
    ]
