# Generated by Django 4.2.4 on 2024-02-13 13:08

import datetime
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_remove_department_code_alter_department_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providers', '0002_transporter_alter_provider_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.CharField(choices=[('Gimi', 'Gimi'), ('GBL', 'GBL'), ('GPB', 'GPB'), ('GS', 'GS'), ('GIR', 'GIR')], default='Gimi', max_length=4, verbose_name='Company')),
                ('request_date', models.DateField(default=datetime.date.today, verbose_name='Request Date')),
                ('motive', models.CharField(max_length=50, verbose_name='Motive')),
                ('obs', models.TextField(verbose_name='Observation')),
                ('status', models.CharField(choices=[('Opened', 'Opened'), ('Pending', 'Pending'), ('Denied', 'Denied'), ('Approved', 'Approved')], default='Pending', max_length=8, verbose_name='Status')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Approval Date')),
                ('cet_number', models.CharField(max_length=20, verbose_name='CET Number')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_approver', to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='FreightQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('status', models.CharField(choices=[('Opened', 'Opened'), ('Pending', 'Pending'), ('Denied', 'Denied'), ('Approved', 'Approved')], default='Pending', max_length=8, verbose_name='Status')),
                ('freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freights.freight')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.transporter')),
            ],
            options={
                'unique_together': {('freight', 'transporter')},
            },
        ),
        migrations.AddField(
            model_name='freight',
            name='quotations',
            field=models.ManyToManyField(through='freights.FreightQuotation', to='providers.transporter', verbose_name='quotations'),
        ),
        migrations.AddField(
            model_name='freight',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_requester', to=settings.AUTH_USER_MODEL, verbose_name='Requester'),
        ),
    ]
