# Generated by Django 4.2.4 on 2024-02-26 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freights', '0002_remove_freight_cet_number_freight_cte_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freight',
            name='execution_date',
        ),
        migrations.AddField(
            model_name='freight',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
    ]
