# Generated by Django 4.2.4 on 2024-03-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freights", "0006_freight_contract_freightquotation_name_other_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="freight",
            name="motive_denied",
            field=models.TextField(blank=True, null=True, verbose_name="Motive Denied"),
        ),
    ]
