# Generated by Django 4.2.4 on 2024-06-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freights', '0010_freight_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Is Internal'),
        ),
    ]
