# Generated by Django 4.2.4 on 2024-06-25 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("freights", "0011_freight_is_internal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freightquotation",
            name="name_other",
        ),
    ]
