# Generated by Django 4.2.4 on 2024-09-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freights", "0012_remove_freightquotation_name_other"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freight",
            name="motive",
            field=models.TextField(verbose_name="Motive"),
        ),
    ]
