# Generated by Django 4.2.4 on 2025-02-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freights', '0013_alter_freight_motive'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightquotation',
            name='name_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name Other'),
        ),
    ]
