# Generated by Django 4.2.4 on 2025-03-06 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_transporter_alter_provider_phone'),
        ('freights', '0015_exportlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightquotation',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.transporter'),
        ),
    ]
