# Generated by Django 4.2.4 on 2024-02-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0002_purchaseproduct_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseproduct",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Quantity"),
        ),
    ]
