# Generated by Django 4.2.4 on 2024-02-26 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0005_purchase_execution_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="execution_date",
        ),
        migrations.AddField(
            model_name="purchase",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created At"
            ),
        ),
    ]
