# Generated by Django 4.2.4 on 2024-03-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0006_remove_purchase_execution_date_purchase_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Approval Date"),
        ),
    ]
