# Generated by Django 4.2.4 on 2024-11-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_alter_purchase_motive'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='motive_denied',
            field=models.TextField(blank=True, null=True, verbose_name='Motive Denied'),
        ),
    ]
