# Generated by Django 4.2.4 on 2024-12-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_alter_purchase_company'),
        ('purchases', '0014_alter_purchase_company'),
    ]

    operations = [
    ]
