# Generated by Django 4.2.4 on 2024-12-27 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0015_merge_20241219_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
