# Generated by Django 4.2.4 on 2025-01-16 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0016_purchaseproduct_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='purchase',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseProduct',
        ),
    ]
