# Generated by Django 4.2.4 on 2024-12-27 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0017_auto_20241227_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
