# Generated by Django 4.2.4 on 2025-01-16 23:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_product_code'),
        ('departments', '0002_remove_department_code_alter_department_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0017_remove_purchaseproduct_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.CharField(choices=[('Gimi', 'Gimi'), ('GBL', 'GBL'), ('GPB', 'GPB'), ('GS', 'GS'), ('GIR', 'GIR'), ('Filial', 'Filial')], default='Gimi', max_length=6, verbose_name='Company')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('request_date', models.DateField(default=datetime.date.today, verbose_name='Request Date')),
                ('motive', models.TextField(verbose_name='Motive')),
                ('obs', models.TextField(verbose_name='Observation')),
                ('status', models.CharField(choices=[('Opened', 'Opened'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Canceled', 'Canceled'), ('Quotation', 'Quotation')], default='Opened', max_length=9, verbose_name='Status')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('has_quotation', models.BooleanField(default=True, verbose_name='Has Quotation?')),
                ('quotation_emails', models.TextField(blank=True, null=True, verbose_name='Purchase Quotation Emails')),
                ('quotation_date', models.DateTimeField(blank=True, null=True, verbose_name='Quotation Date')),
                ('control_number', models.IntegerField(default=0, verbose_name='Control Number')),
                ('motive_denied', models.TextField(blank=True, null=True, verbose_name='Motive Denied')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Approver', to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='Quantity')),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Price')),
                ('status', models.CharField(choices=[('Opened', 'Opened'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Canceled', 'Canceled'), ('Quotation', 'Quotation')], default='Opened', max_length=9, verbose_name='Status')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='products',
            field=models.ManyToManyField(through='purchases.PurchaseProduct', to='products.product', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Requester', to=settings.AUTH_USER_MODEL, verbose_name='Requester'),
        ),
    ]
