# Generated by Django 4.2.4 on 2025-01-12 23:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0018_auto_20241227_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
