# Generated by Django 4.2.4 on 2025-02-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0018_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='approval_date',
            new_name='approval_date_director',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='approver',
            new_name='approver_director',
        ),
    ]
