# Generated by Django 4.2.4 on 2025-04-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0015_merge_20241223_0825'),
        ('purchases', '0018_initial'),
    ]

    operations = [
    ]
