# Generated by Django 4.2.4 on 2025-02-11 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0019_rename_approval_date_purchase_approval_date_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='approval_date_manager',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approval Date Manager'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='approver_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_manager', to=settings.AUTH_USER_MODEL, verbose_name='Approver Manager'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quotation_link',
            field=models.URLField(blank=True, null=True, verbose_name='Quotation Link'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='approver_director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver_director', to=settings.AUTH_USER_MODEL, verbose_name='Approver Director'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Canceled', 'Canceled'), ('Quotation', 'Quotation'), ('Validation', 'Validation')], default='Opened', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Canceled', 'Canceled'), ('Quotation', 'Quotation'), ('Validation', 'Validation')], default='Opened', max_length=10, verbose_name='Status'),
        ),
    ]
