# Generated by Django 4.2.4 on 2025-01-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0019_remove_purchaseproduct_id_alter_purchaseproduct_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseproduct',
            old_name='uuid',
            new_name='id',
        ),
    ]
