# Generated by Django 4.2.4 on 2025-02-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0020_purchase_approval_date_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='omie_total',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12, verbose_name='Omie Total'),
        ),
    ]
