# Generated by Django 4.2.4 on 2025-01-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0020_rename_uuid_purchaseproduct_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseproduct',
            old_name='id',
            new_name='uuid',
        ),
    ]
