# Generated by Django 4.2.4 on 2025-03-14 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0021_purchase_omie_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=255)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('approved_manager_date', models.DateField(blank=True, null=True)),
                ('approved_director_date', models.DateField(blank=True, null=True)),
                ('purchased_date', models.DateField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('arrival_forecast_date', models.DateField(blank=True, null=True)),
                ('delivered_order_date', models.DateField(blank=True, null=True)),
                ('nf_entry_date', models.DateField(blank=True, null=True)),
                ('nf_number', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase')),
            ],
        ),
    ]
