# Generated by Django 4.2.4 on 2025-01-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0021_rename_id_purchaseproduct_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseproduct',
            old_name='uuid',
            new_name='id',
        ),
    ]
