# Generated by Django 4.2.4 on 2024-11-21 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_remove_department_code_alter_department_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.CharField(editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('position', models.CharField(max_length=50, verbose_name='Name')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='departments.department')),
            ],
        ),
    ]
