# Generated by Django 4.2.4 on 2024-11-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_position_department_alter_position_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='company',
            field=models.CharField(blank=True, choices=[('Gimi', 'Gimi'), ('GBL', 'GBL'), ('GPB', 'GPB'), ('GS', 'GS'), ('GIR', 'GIR')], default='Gimi', max_length=4, null=True, verbose_name='Company'),
        ),
    ]
