# Generated by Django 4.2.4 on 2024-11-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_position_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='company',
            field=models.CharField(choices=[('Gimi', 'Gimi'), ('GBL', 'GBL'), ('GPB', 'GPB'), ('GS', 'GS'), ('GIR', 'GIR')], default='Gimi', max_length=4, verbose_name='Company'),
        ),
    ]
