# Generated by Django 4.2.4 on 2024-11-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_position_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='department',
            new_name='cost_center',
        ),
    ]
