# Generated by Django 4.2.4 on 2024-11-22 01:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_remove_department_code_alter_department_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0006_rename_department_position_cost_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.CharField(choices=[('Gimi', 'Gimi'), ('GBL', 'GBL'), ('GPB', 'GPB'), ('GS', 'GS'), ('Grupo', 'Grupo')], default='Gimi', max_length=5, verbose_name='Company')),
                ('request_date', models.DateField(default=datetime.date.today, verbose_name='Request Date')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('is_replacement', models.BooleanField(verbose_name='Is Replacement')),
                ('has_pc', models.BooleanField(verbose_name='Has Pc')),
                ('needs_phone', models.BooleanField(verbose_name='Needs Phone')),
                ('needs_tablet', models.BooleanField(verbose_name='Needs Tablet')),
                ('needs_software', models.BooleanField(verbose_name='Needs Software')),
                ('software_names', models.CharField(blank=True, max_length=60, null=True, verbose_name='Software Names')),
                ('has_workstation', models.BooleanField(verbose_name='Has Workstation')),
                ('motive', models.CharField(max_length=120, verbose_name='Motive')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('status', models.CharField(choices=[('Opened', 'Opened'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Canceled', 'Canceled'), ('Quotation', 'Quotation')], default='Opened', max_length=9, verbose_name='Status')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('replaced_email', models.CharField(blank=True, max_length=60, null=True, verbose_name='Replacement Email')),
                ('complete_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Complete Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('control_number', models.IntegerField(default=0, verbose_name='Control Number')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('cost_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
