# Generated by Django 4.2.4 on 2024-11-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.CharField(choices=[('Gimi', 'Gimi'), ('GBL', 'GBL'), ('GPB', 'GPB'), ('GS', 'GS'), ('Group', 'Group')], default='Gimi', max_length=5, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='motive',
            field=models.TextField(verbose_name='Motive'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='software_names',
            field=models.TextField(blank=True, null=True, verbose_name='Software Names'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Canceled', 'Canceled')], default='Opened', max_length=9, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='position',
            name='company',
            field=models.CharField(choices=[('Gimi', 'Gimi'), ('GBL', 'GBL'), ('GPB', 'GPB'), ('GS', 'GS'), ('Group', 'Group')], default='Gimi', max_length=5, verbose_name='Company'),
        ),
    ]
