# Generated by Django 4.2.4 on 2024-11-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_company_alter_employee_motive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Denied', 'Denied'), ('Approved', 'Approved')], default='Opened', max_length=9, verbose_name='Status'),
        ),
    ]
