# Generated by Django 4.2.4 on 2024-11-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default=1, max_length=50, verbose_name='Position'),
            preserve_default=False,
        ),
    ]
