# Generated by Django 4.2.4 on 2024-11-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='c1de8df7-c0f8-4c81-86c0-af2acd22fc73', max_length=50, verbose_name='Position'),
            preserve_default=False,
        ),
    ]
