# Generated by Django 4.2.4 on 2024-11-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.position',default='c1de8df7-c0f8-4c81-86c0-af2acd22fc73'),
            preserve_default=False,
        ),
    ]
