# Generated by Django 4.2.4 on 2024-01-31 17:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.CharField(choices=[('Gimi', 'Gimi'), ('GBL', 'GBL'), ('GPB', 'GPB'), ('GS', 'GS'), ('GIR', 'GIR')], default='Gimi', max_length=4, verbose_name='Company')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('motive', models.CharField(max_length=50, verbose_name='Motive')),
                ('obs', models.TextField(verbose_name='Observation')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved?')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisitions.requisition')),
            ],
            options={
                'unique_together': {('requisition', 'product')},
            },
        ),
        migrations.AddField(
            model_name='requisition',
            name='products',
            field=models.ManyToManyField(through='requisitions.RequisitionProduct', to='products.product', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
