# Generated by Django 4.2.4 on 2024-01-31 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_remove_department_code_alter_department_id'),
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Department'),
        ),
    ]
